AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dummy

  Dummy

Globals:
  Function:
    Timeout: 15
    MemorySize: 128
    Environment:
      Variables:
        TARGET_BUCKET: test-ehdez

Resources:
  DummyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
